### ISSUE TITLE
无法渲染react组件

### ISSUE THREAD

**Issue by justoneone** [cvnine/vitepress-rc#1]
从[演示页](https://cvnine.github.io/vitepress-rc/)进去点击[组件演示](https://cvnine.github.io/vitepress-rc/local/dif.html)，在loading后无法渲染react组件。

错误信息：
TypeError: Failed to fetch dynamically imported module: https://jspm.dev/gogocode@0.2.9

**Comment by ihupoo** [comment]
gogocode 0.2.9 所依赖的一个包在jspm上404了。
打算抛弃gogocode，直接使用babel的ast解析出需要的内容，还能加快加载速度。原生import依赖太多太慢了。

**Comment by ihupoo** [comment]
v0.0.13 版本已修复

**Comment by justoneone** [comment]
不错哦，谢谢
